#
# Makefile for GCC
#
#
# prerequisite libraries: boost, boost-devel
#


OBJECTS = main.o comp.o fft.o

CC_OPTS = -c -O3 -ffast-math -fopenmp
EXE_NAME = imgalt

all: $(EXE_NAME)

clean:
	rm $(OBJECTS)
	rm $(EXE_NAME)

$(EXE_NAME): $(OBJECTS)
	g++ $(OBJECTS) -fopenmp -lboost_system -lboost_filesystem -lboost_chrono -o $(EXE_NAME)

main.o: main.cpp
	g++ $(CC_OPTS) main.cpp

comp.o: comp.cpp
	g++ $(CC_OPTS) comp.cpp

fft.o: fft.cpp
	g++ $(CC_OPTS) fft.cpp
