name: C/C++ CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo rm -rf /usr/local/share/boost/1.69.0
        export APT_DEPENDENCIES="libboost-dev libboost"
        sudo apt-get update -qq
        sudo apt-get install -qq ${APT_DEPENDENCIES}
    - name: make
      run: make -f Makefile.gcc

